
-- В настройках сервисов мы предполагаем что
-- ip:			192.168.13.129
-- port:		5432
-- user:		postgres
-- password:	postgres

-- Create database
CREATE DATABASE grochery_db
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
-- product для ws-product
CREATE TABLE IF NOT EXISTS product(
	product_id long PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	product_name varchar(300) NOT NULL CHECK (product_name <> '')

);

INSERT INTO product(product_name) values ('Картофель 1 кг.');
INSERT INTO product(product_name) values ('Капуста 1 кг.');
INSERT INTO product(product_name) values ('Морковь 1 кг.');
INSERT INTO product(product_name) values ('Яблоки 1 кг.');
INSERT INTO product(product_name) values ('Мандарины 1 кг.');
INSERT INTO product(product_name) values ('Апельсины 1 кг.');
